### ISSUE TITLE
Example to style cursor pointer animation

### ISSUE THREAD

**Issue by Marlysson** [luisvinicius167/ityped#2]
I saw that you use in the examples in final of README to animate cursor , this:

```css
@keyframes blink{
    0% { opacity:1; }
    50% { opacity:0; }
    100% { opacity:1; }
}
```

You can use the property ```animation-direction``` using the reverse or alternate value , to no  need apply the same state  of moment 0%at moment 100% .

That it just apply the same effect start's animation.
